# Generated by Django 3.2 on 2022-11-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ml_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='TITLE')),
                ('version', models.FloatField(verbose_name='VERSION')),
                ('is_selected', models.BooleanField(verbose_name='IS_SELECTED')),
                ('date_published', models.DateField(auto_now_add=True, verbose_name='DATE_PUBLISHED')),
            ],
        ),
    ]
