# Generated by Django 3.2 on 2022-11-22 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml_model',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='models/'),
            preserve_default=False,
        ),
    ]
