# Generated by Django 3.2 on 2022-11-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_auto_20221122_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_model',
            name='model_file',
            field=models.FileField(upload_to='models/', verbose_name='MODEL_FILE'),
        ),
    ]
