# Generated by Django 3.2 on 2022-11-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_alter_ml_model_model_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ml_model',
            options={'ordering': ('id',)},
        ),
    ]
