# Generated by Django 3.2 on 2022-11-23 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_alter_ml_model_file'),
        ('ml', '0005_alter_ml_model_options'),
    ]

    operations = [
    ]
