# Generated by Django 3.2 on 2022-11-23 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0006_merge_20221123_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ml_model',
            name='file',
        ),
    ]
