# Generated by Django 3.2 on 2022-11-23 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0007_remove_ml_model_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_model',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='IS_SELECTED'),
        ),
        migrations.AlterField(
            model_name='ml_model',
            name='version',
            field=models.FloatField(default=1.0, verbose_name='VERSION'),
        ),
        migrations.CreateModel(
            name='evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0, verbose_name='TOTAL')),
                ('success', models.IntegerField(default=0, verbose_name='SUCCESS')),
                ('ml_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ml.ml_model')),
            ],
        ),
    ]
