# Generated by Django 3.2 on 2022-11-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0008_auto_20221123_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_model',
            name='model_file',
            field=models.FileField(blank=True, upload_to='models/', verbose_name='MODEL_FILE'),
        ),
    ]
